#!/bin/bash

# https://wiki.archlinux.org/index.php/iptables

# For every arriving packets (from the Internet), we will transform 125.227.38.80 into 10.15.20.1 (gateway IP)
iptables -t nat -A PREROUTING -d 125.227.38.80 -j DNAT --to-destination 10.15.20.1
# For every packets generated by this container, we will transform 125.227.38.80 into 10.15.20.1 (gateway IP)
iptables -t nat -A OUTPUT -d 125.227.38.80 -j DNAT --to-destination 10.15.20.1
